
DROP PROCEDURE IF EXISTS edit_list(INT, VARCHAR(63), VARCHAR(1023), INT, INT);
DROP FUNCTION IF EXISTS buy(VARCHAR(63), INT, INT);

DROP TABLE IF EXISTS List;
DROP TABLE IF EXISTS Transaction;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Item;